variables:
  DOCKER_IMAGE_NAME: $REGISTRY_USER/hoewarmishetindelft
  DOCKER_IMAGE_TAG: python3_script

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS 
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG ./
    - docker run --rm $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG echo "Docker image runs successfully"
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  only:
    changes:
      - Dockerfile
      - "*.py"
      - .gitlab-ci.yml

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  needs:
    - build
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS 
  script:
    - docker pull $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run --name $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME


