stages:
  - build
#  - deploy

variables:
  DOCKER_IMAGE_NAME: "hoewarmishetindelft"
  DOCKER_IMAGE_TAG: "CodiLime"

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker run --name $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME

#deploy:
#  stage: deploy
#  image: docker:stable
#  services:
#    - docker:dind
#  script:
