stages:
  - build

variables:
  DOCKER_IMAGE_NAME: "hoewarmishetindelft"
  #DOCKER_IMAGE_TAG: "CodiLime"

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker run --name $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME
