variables:
  DOCKER_IMAGE_NAME: "hoewarmishetindelft"
  DOCKER_IAMGE_TAG: "simple"

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS 
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

deploy:
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker run $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

