variables:
  DOCKER_IMAGE_NAME: "hoewarmishetindelft"
  DOCKER_BUILDKIT: "1"

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  services:
    - docker:dind
  script:
    - docker run --name $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME

