variables:
  DOCKER_IMAGE_NAME: $REGISTRY_USER/hoewarmishetindelft
  APP_NAME: hoewarmishetindelft
  DOCKER_IMAGE_TAG: python3_script

stages:
  - test
  - build
  - deploy

run-test:
  stage: test
  image: python:3.11.8
  only:
    changes:
      - src/*.py
      - src/requirements.txt
      - .gitlab-ci.yml
  before_script:
    - pip install -r src/requirements.txt
  script:
    - python src/TestHoeWarmIsHetInDelft.py

create-build:
  stage: build
  needs:
    - run-test
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG ./
    - docker run --rm $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG echo "Docker image runs successfully"
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

deploy-image:
  stage: deploy
  needs:
    - create-build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker pull $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run --name $APP_NAME $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG


