stages:
  - deploy

variables:
  DOCKER_IMAGE_NAME: "HoeWarmIsHetInDelft"
  DOCKER_VERSION: "cli"

deploy:
  stage: deploy
  image: docker:$DOCKER_VERSION
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker run -d --name $DOCKER_IMAGE_NAME $DOCKER_IMAGE_NAME