stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: "hoewarmishetindelft"
  DOCKER_IMAGE_TAG: "latest"

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker run --rm $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
