name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: python-3.11.8

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Run tests
        run: python src/TestHoeWarmIsHetInDelft.py

  build:
    runs-on: docker-stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build . --file dockerfile \
          --tag ${{ github.repository_owner }}/hoewarmishetindelft:python3_script \
          --tag ${{ github.repository_owner }}/hoewarmishetindelft:latest

  deploy:
    runs-on: docker-stable

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ${{ github.repository_owner }}/hoewarmishetindelft:python3_script
          docker push ${{ github.repository_owner }}/hoewarmishetindelft:latest
